### ISSUE TITLE
Google Workspace DPC Extras for Zero touch provisioning

### ISSUE THREAD

**Issue by Kurrams** [jasonbayton/11ty#25]
**Google Workspace DPC Extras for Zero touch provisioning**
Hi Jayson, 
 You can add the following DPC for Google Workspace Zero Touch Provisioning. Official Reference is added. 
*[Official Reference](https://support.google.com/a/answer/9508498?hl=en)*_

<img width="539" alt="GoogleWorkspaceDPC" src="https://user-images.githubusercontent.com/107587130/188308550-d5ee29f5-c4fd-44c3-b0f9-6a21b5fb3e73.PNG">

Thanks. 

Regards,
Khurram

**Comment by jasonbayton** [comment]
Thanks!

https://github.com/jasonbayton/11ty/commit/936d780bdab2aad48a16ca05d51c4a278df0ee12
