### ISSUE TITLE
Redis - Add a hint that the redis socket file in /etc/redis/redis.conf might be different

### ISSUE THREAD

**Issue by rakurtz** [jasonbayton/11ty#52]
It is easily to be overlooked by the reader that the commented line on unix systems might be looking like this:

```#unixsocket /var/run/redis/redis-server.sock```

instead of this as stated in the article:

```unixsocket /var/run/redis/redis.sock```

so when the reader just removes the comment and later adds `/var/run/redis/redis.sock` to his nextcloud config file, he will encounter a serious bug.

**Comment by jasonbayton** [comment]
Hi @rakurtz 

Are you referring to this line in this doc? -

https://github.com/jasonbayton/11ty/blob/main/_src/docs/nextcloud/installing-nextcloud-on-ubuntu-16-04-lts-with-redis-apcu-ssl-apache.md#L438

If no, could you link directly to the line of concern please?

**Comment by rakurtz** [comment]
Hey Jason,

yes, i think we are talking about the same lines. Since your link isn’t getting me to a specific line, i am sending you a screenshot of that lines.

Thank you for your reply and for your nice documentation.

Best
Martin

￼

**Comment by jasonbayton** [comment]
Hi Martin, 

No image attached I'm afraid, this is the line I linked to, 438 - 

<img width="824" alt="image" src="https://github.com/jasonbayton/11ty/assets/3178412/3b699588-621d-4962-b3ec-9fbfc0fc3e29">

**Comment by rakurtz** [comment]
Exactly :)

Best regards and thank you so much for your documentation. It helped me a lot (also in the last years from time to time)




Mit freundlichen Grüßen
Martin Kurtz


----------------------------------------------
Martin Kurtz

Kurtz.Lynen Rechtsanwälte
Aarstraße 143-145
65232 Taunusstein

06128 48846 0
***@***.***

Am 14.11.2023 um 13:33 schrieb Jason Bayton ***@***.***>:

﻿

Hi Martin,

No image attached I'm afraid, this is the line I linked to, 438 -

[image]<https://user-images.githubusercontent.com/3178412/282775327-3b699588-621d-4962-b3ec-9fbfc0fc3e29.png>

**Comment by jasonbayton** [comment]
Voila (https://github.com/jasonbayton/11ty/commit/6bcd56e4d2c1bb863a85a1658822499e15d63587)

Thank you for contributing! :)
