### ISSUE TITLE
[Bug] LXD tag fails with 404

### ISSUE THREAD

**Issue by GrahamEnigma** [jasonbayton/11ty#71]
**Describe the bug**

**To Reproduce**
1. Go to '.https://bayton.org/docs/linux/lxd/mount-cifssmb-shares-rw-in-lxd-containers/' 
2. Click on 'So continuing the recent [LXD theme](https://bayton.org/tag/lxd/), in this article we’ll work through mounting CIFs shares read/write on containers.'
4. See error https://bayton.org/tags/lxd/

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jasonbayton** [comment]
https://github.com/jasonbayton/11ty/commit/ca29b1463201f1ea9d26b7b5ab8b7e4fedac56a2

Thank you!
